### ISSUE TITLE
Netatop broken under kernel 5.6

### ISSUE THREAD

**Issue by frankspace** [Atoptool/atop#107]
Attempting to compile netatop with kernel 5.6 fails.  I don't claim to be clever enough to comprehend why, but the most salient-looking messages appear to be `"invalid use of undefined type 'struct timespec'" regarding "boottime"`; and "`implicit declaration of function 'getboottime'; did you mean 'getboottime64'?"`  When I tried just blindly changing "getboottime" to "getboottime64" in netatop.c, I got another error telling me this was an incompatible pointer type.  Presumably, the linux kernel devs continued the same tampering that resulted in breakage under 5.5, but I am insufficiently knowledgeable to look into it further.

**Comment by Atoptool** [comment]
This issue is solved with version 3.1 of netatop.
