### ISSUE TITLE
Add ZFS support for zfsonlinux users (otherwise the memory stats in atop will be misleading)

### ISSUE THREAD

**Issue by gleventhal** [Atoptool/atop#109]
Systems using the ZFS filesystem have misleading memory info within atop due to the ARC in ZFS not being represented in atop.

Please parse /proc/spl for people using zfsonlinux so that we can properly attribute ZFS memory usage in atop.

**Comment by gleventhal** [comment]
@Atoptool ping?  This is really a must for zfsonlinux users, otherwise the MEM stats are just misleading.

**Comment by Atoptool** [comment]
A new counter `zfarc` has been added to the memory utilization metrics on system level and to the parsable output.

**Comment by gleventhal** [comment]
Thanks very much for your work on this!
