### ISSUE TITLE
Can atopacctd work inside lxc container?

### ISSUE THREAD

**Issue by varuzam** [Atoptool/atop#11]
Hi
atopacctd can not start inside lxc container with debian 9

```
~# atopacctd -V
Version: 2.2.6 - 2016/12/22 00:00:00  <gerlof.langeveld@atoptool.nl>

~# /usr/sbin/atopacctd
receive NETLINK family, errno -2
^C
```

**Comment by ikus060** [comment]
This issue also cause me problem when trying to upgrade from Debian Dessie to Debian Stretch ifatop is installed.

**Comment by fevangelou** [comment]
Still broken in v2.3.0 (latest at the time) on Ubuntu 18.04 (as LXC container OS).

Any update @Atoptool?

**Comment by fevangelou** [comment]
```
$ systemctl status atopacct.service
* atopacct.service - Atop process accounting daemon
   Loaded: loaded (/lib/systemd/system/atopacct.service; enabled; vendor preset: enabled)
   Active: failed (Result: protocol) since Thu 2018-09-13 01:06:46 EEST; 43s ago
     Docs: man:atopacctd(8)
  Process: 24080 ExecStart=/usr/sbin/atopacctd (code=exited, status=0/SUCCESS)

Sep 13 01:06:46 server-hostname-here systemd[1]: Starting Atop process accounting daemon...
Sep 13 01:06:46 server-hostname-here atopacctd[24080]: /run/pacct_shadow.d: File exists
Sep 13 01:06:46 server-hostname-here systemd[1]: atopacct.service: Can't open PID file /run/atopacctd.pid (yet?) after start: No such file or directory
Sep 13 01:06:46 server-hostname-here systemd[1]: atopacct.service: Failed with result 'protocol'.
Sep 13 01:06:46 server-hostname-here systemd[1]: Failed to start Atop process accounting daemon.
```
...on a newly installed Proxmox 5 LXC container running Ubuntu 18.04.

**Comment by keesbos** [comment]
# atopacctd -V
Version: 2.3.0 - 2017/03/25 09:59:59  <gerlof.langeveld@atoptool.nl>

Probably related to privileges 

part of a strace:
9301  connect(4, {sa_family=AF_UNIX, sun_path="/dev/log"}, 110) = 0
9301  sendto(4, "<30>Nov 13 17:05:17 atopacctd[93"..., 105, MSG_NOSIGNAL, NULL, 0) = 105
9301  getpriority(PRIO_PROCESS, 0)      = 20
9301  setpriority(PRIO_PROCESS, 0, -39) = -1 EACCES (Permission denied)
9301  socket(AF_NETLINK, SOCK_RAW, NETLINK_GENERIC) = 5
9301  setsockopt(5, SOL_SOCKET, SO_RCVBUF, [262144], 4) = 0
9301  bind(5, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 0
9301  getpid()                          = 9301
9301  sendto(5, {{len=36, type=nlctrl, flags=NLM_F_REQUEST, seq=0, pid=9301}, "\x03\x01\x00\x00\x0f\x00\x02\x00\x54\x41\x53\x4b\x53\x54\x41\x54\x53\x00\x00\x00"}, 36, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 36
9301  recvfrom(5, {{len=56, type=NLMSG_ERROR, flags=0, seq=0, pid=9301}, {error=-ENOENT, msg={{len=36, type=nlctrl, flags=NLM_F_REQUEST, seq=0, pid=9301}, "\x03\x01\x00\x00\x0f\x00\x02\x00\x54\x41\x53\x4b\x53\x54\x41\x54\x53\x00\x00\x00"}}}, 2068, 0, NULL, NULL) = 56
9301  write(2, "receive NETLINK family, errno -2"..., 33) = 33

**Comment by Atoptool** [comment]
I can reproduce this issue with a container in my Docker environment. Even when running a privileged container, this error occurs.
I investigated the kernel source code, but could not find the real cause of this error. Anyhow, this is not something I can solve in atop. It really is another behavior of NETLINK sockets when used within a container.

**Comment by datenfalke** [comment]
Same here in Proxmox-LXC container: When upgrading from Debian Jessie to Stretch, the apt upgrade process is hanging:

    atop (2.2.6-4) wird eingerichtet ...
    Neue Version der Konfigurationsdatei /etc/cron.d/atop wird installiert ...
    Neue Version der Konfigurationsdatei /etc/default/atop wird installiert ...
    Neue Version der Konfigurationsdatei /etc/init.d/atop wird installiert ...
    receive NETLINK family, errno -2

**Comment by keesbos** [comment]
For me (bionic container) the install finishes when I create a dummy /run/atopacctd.pid

```
echo $$ >/run/atopacctd.pid
# apt install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up atop (2.3.0-1) ...
W: APT had planned for dpkg to do more than it reported back (0 vs 4).
   Affected packages: atop:amd64
```

**Comment by immanuelfodor** [comment]
Tried the fake pid hack above (https://github.com/Atoptool/atop/issues/11#issuecomment-529889141) but it doesn't work on a Debian 10 LXC over latest Proxmox, systemctl status shows the below line and apt fails to finish installing the package:

```
Jul 01 21:17:39 rke-pbs systemd[1]: atopacct.service: New main PID 2494 does not exist or is a zombie.
```
