### ISSUE TITLE
Short lived threads show as processes

### ISSUE THREAD

**Issue by ReubenM** [Atoptool/atop#112]
I'm viewing recorded data from a raw file, and I have a tomcat process with a lot of threads. If a thread starts and exits in-between atop's aggregation interval, the thread is displayed as a process (i.e. not shown under the process when toggling using 'y') with a GID, but no TID, and bogus EUID and GUID displaying as root. Perhaps an issue with process accounting dealing with threads?

**Comment by Atoptool** [comment]
Process accounting only records terminated processes, not terminated threads. So if a thread starts and finishes within an atop interval, usually you can't see any information about such thread in the atop output (with key 'y').
I tried to reproduce your situation with a small C program using pthreads, but I can't see any of the output that you describe. Can you please provide more information?

**Comment by ReubenM** [comment]
I'm attaching a raw atop file. This is from a performance testing environment, and as you page through the file you start to see java threads showing as processes. Things like hotspot compiler threads show up quite frequently.
[atop.bin.zip](https://github.com/Atoptool/atop/files/4743024/atop.bin.zip)

**Comment by Atoptool** [comment]
Thanks for the raw atop file. It really helped analyzing the issue:
When the main thread of a multi-threaded process terminates (i.e. the process terminates) while there are still other threads present in the process, the name of one of the other threads is written as the process name in the process accounting record.

For multi-threaded processes that do not give individual threads specific names (all threads have the process name), obviously you won't notice this issue. 
When the main thread would have joined on the other threads first, you won't notice this issue either.

This issue can be reproduced by the following test program
(compile with: gcc prog.c -o prog -lpthread):

#define	_REENTRANT
#include <sys/types.h>
#include <pthread.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
	void 		*mythread(void *);
	pthread_t 	tid1, tid2;
	int		i;

	pthread_create(&tid1, (pthread_attr_t *)0, mythread, (void *) 0);
	pthread_setname_np(tid1, "WORKER-1");

	pthread_create(&tid2, (pthread_attr_t *)0, mythread, (void *) 0);
	pthread_setname_np(tid2, "WORKER-2");

	sleep(10);

	return 0;
}

void *
mythread(void *dummy)
{
	while(1);	// keep working!
}


After the process has terminated, most probably the name "WORKER-2" is the process name in the process accounting record.

**Comment by Atoptool** [comment]
Please report this as a kernel issue.

**Comment by ReubenM** [comment]
I want to make sure I understand the scope of this. Is this just a change in name that effects how the process is visually displayed, or can this also erroneously effect the metrics that are reported?

**Comment by Atoptool** [comment]
As far as I can judge (by experiment and viewing the kernel code in kernel/acct.c) it does not influence the metrics. When you run the test program listed above, you can see in the atop output that the real time of the process is 10 seconds and the CPU time consumed is close to 20 seconds (i.e. the total CPU consumption of both threads).

**Comment by ReubenM** [comment]
What worries me is that the system being perf tested had some minor java and tomcat updates, but the CPU utilization almost doubled. One of the changes was that before the update, all the java threads did not have names (just showed as "java") and after the update the threads were all named. I just want to be certain there is not a scenario taking place where the process accounting is somehow erroneously led to believe that an exiting thread is the process exiting, resulting the utilization metrics getting counted twice: once from the normal process monitoring, and a second time from a broken process accounting tripped up by java's thread model.
