### ISSUE TITLE
Bug: Race in process accounting

### ISSUE THREAD

**Issue by gleventhal** [Atoptool/atop#115]
I have seen this bug occur in 2.3.x, 2.4.x and now 2.5.x:

There is a race around atop's shadow file access and the cleanup of those files in atopacctd:

Reproducer:
Modified acctproc.c
```
--- acctproc.c	2019-01-12 17:37:19.000000000 -0500
+++ acctproc.c	2020-06-02 13:20:45.708430504 -0400
@@ -266,8 +266,9 @@
 
 		if ( (cfp = fopen(shadowpath, "r")) )
 		{
-			if (fscanf(cfp, "%ld/%lu",
-					&curshadowseq, &maxshadowrec) == 2)
+			int fscanres;
+			if ((fscanres = fscanf(cfp, "%ld/%lu",
+					&curshadowseq, &maxshadowrec)) == 2)
 			{
 				fclose(cfp);
 
@@ -321,13 +322,26 @@
 
                        			(void) close(acctfd);
 				}
+				else
+				{
+					perror("open shadowpath");
+					abort();
+				}
 			}
 			else
 			{
+				perror("fscanf");
+				printf("fscanf returned %i\n", fscanres);
+				abort();
 				fclose(cfp);
 				maxshadowrec = 0;
 			}
 		}
+		else
+		{
+			perror("fopen");
+			abort();
+		}
 
 		(void) semop(sempacctpubid, &semrelse, 1);
 	}


--- atop.c	2019-01-12 17:37:19.000000000 -0500
+++ atop.c	2020-06-02 13:04:32.382560044 -0400
@@ -679,6 +679,8 @@
 	** (remaining) resource-usage by processes which have finished
 	*/
 	acctreason = acctswon();
+	printf("acctswon returned %d\n", acctreason);
+	cleanstop(0);
 
 	/*
 	** determine properties (like speed) of all interfaces

```

Then in a shell, run:
```
while true; do atop -w /var/log/atoptest ; [ "$?" -eq 0 ] || break;  done
```

In another shell window:
```
# Cause atopacctd to clean up shadow files
systemctl start atop
systemctl stop atop
```
Strace output of atopacctd when systemctl stop atop is run:
```
open("/var/run/pacct_shadow.d/0000000000.paf", O_WRONLY) = 6 

unlink("/var/run/pacct_shadow.d/0000000000.paf") = 0 

creat("/var/run/pacct_shadow.d/0000000000.paf", 0644) = 1
```
As you can imagine, the fscanf in acctswon will not return 2 if it falls within this window.

Output:
```
acctswon returned 0
acctswon returned 0
acctswon returned 0
acctswon returned 0
fscanf: Success
fscanf returned -1
Aborted (core dumped)
```

**Comment by gleventhal** [comment]
I think I see what goes wrong here:

In acctproc.c when going from atop 2.3.0 to atop 2.4.0, you did this:

```
@@ -822,7 +833,8 @@ 			** determine the size of the new (current) account file 			** and initialize the current offset within that file 			*/-			(void) fstat(acctfd, &statacc);+			if (fstat(acctfd, &statacc) == -1)+				return 0;  			acctsize  = 0;
```

Which, if the fstat fails, makes you miss out on this code, later in the same function:

```
        else
        /*
        ** classic process accounting on bases of directly opened
        ** process accounting file
        */
        {
                if (acctsize > statacc.st_size) /* accounting reset? */
                {
                        /*
                        ** reposition to start of file
                        */
                        (void) lseek(acctfd, 0, SEEK_SET);
                        acctsize = 0;
                }

                return (statacc.st_size - acctsize) / acctrecsz;
        }
}
```

**Comment by gleventhal** [comment]
There is also an underlying bug in atopacctd dealing with the shadow file which has exited since 2.3.0 I believe, but the code change in >= 2.4.0 causes that bug to be more harmful.  It seems not exiting from acctprocnt on the fstat failure papered-over the issue.

I'll try to get you a repro in case this doesn't all make sense already.

**Comment by gleventhal** [comment]
In this scenario I can see that atopacctd has /run/pacct_shadow.d/0000000000.paf opened but atop has /var/cache/atop.d/atop.acct opened.

I also see that atop runs switchshadow many times, getting ENOENT on each attempted open for the next sequence of shadow file (.paf)

**Comment by gleventhal** [comment]
I think a major change that made the bug have more impact is the change from int to ulong on nprocexit and acctphotoproc

**Comment by gleventhal** [comment]
One codepath that seems indicative of the bug is "reactivating process accounting" from atopacctd.c

When you see that, you will find an empty shadow file referenced by atopacctd and /var/cache/atop.d/atop.acct referenced by atop

Since nothing major changed in this file, I suspect the bug exists in 2.3.0 too, but the uint vs ulong
made it less obvious.

@Atoptool

**Comment by gleventhal** [comment]
I now have proof that this race also exists in 2.3.0.  In some cases noverflow grows massively large and the log gets huge, in other cases #exit stays at zero and the #proc numbers seem to be wrong as well.  

This happens after an hour of launching atop, when atopacctd logs "reactivating process accounting"

**Comment by gleventhal** [comment]
if the 
```
if ( (cfp = fopen("shadowpath", "r")) )
```

in acctproc.c fails, atop will successfully use classic process accounting for 1 hour, after which, atopacctd tries to reactivate acct() leaving atop process-accounting in a broken state where it looks to /var/cache/atop.d/atop.acct which is no longer being written to and atopacctd looks to an empty shadow file.

**Comment by gleventhal** [comment]
I have added a 2 second sleep in between the stop and start of atop every night and that has resolved the issue for me, so I am pretty sure it's gcshadows in atopacctd that races the stop and start of atop.

**Comment by Atoptool** [comment]
Can you please verify if the message "switching to polling mode" can be found in the /var/log/messages file (or /var/log/syslog)?

**Comment by Atoptool** [comment]
Currently testing a solution for this issue...

**Comment by gleventhal** [comment]
I am pretty sure that I don't see "switching to polling mode" in any logs, but I will go double check in a little bit.

**Comment by gleventhal** [comment]
Confirming that we do not ever hit that branch which logs "switching to polling mode".  atopaccthas a fd opened for the shadow file and atop has an fd open for /var/cache/atop.d/atop.acct when this issue occurs, and that never gets rectified.  It seems that during this time, atop is performing process accounting successfully until atopacctd logs "reactivate process accounting"  then the fds are still pointing to different files, but I suspect acct() is no longer writing to the /var/cache/atop.d/atop.acct file Which is why accounting stops at that time.

**Comment by Atoptool** [comment]
Could you please verify the current solution?

**Comment by gleventhal** [comment]
So far this solution does appears to work.  More specifically, my reproducer does not reproduce the issue anymore.  I'll think of some more tests, but I am cautiously optimistic.  Thanks for addressing!

**Comment by Atoptool** [comment]
Issue has been solved.
