### ISSUE TITLE
If tmpfs on /run fills, atopacctd will crash and cannot restart until someone does rm -rf /run/pacct_shadow.d/

### ISSUE THREAD

**Issue by gleventhal** [Atoptool/atop#121]
If the shadow file exists and is invalid, atopacctd should handle that on startup by removing or renaming it.  Currently, when the tmpfs fills up due to the box OOM-ing, atopacctd doesn't handle this scenario and cannot restart on its own without intervention.

**Comment by Atoptool** [comment]
After a restart of atopacctd, the shadow directory will be renamed and recreated.
