### ISSUE TITLE
Can the absence of an essential process be detected in the atop recordings?

### ISSUE THREAD

**Issue by jerkstorecaller** [Atoptool/atop#122]
I'm reading up about atop and it seems great for reviewing a system's history while troubleshooting.

Does atop provide a way to track not just processes whose resource consumption changed, but also track the presence of one specific process at all times, for example /usr/local/bin/EssentialDaemon?

Scenario: EssentialDaemon crashes occasionally, and gets auto-restarted within a second. I want to detect this situation.

I can track these crashes via external mechanisms (easiest being to append a timestamp to a log file on launch), but then this becomes an additional file to check to view a system's history instead of just the atop recordings.

A PID change can be used to detect this while browsing history, I realize.

**Comment by gleventhal** [comment]
Just check for Exited processes with the name in atop's Parsable API, for instance, assuming your process has no spaces in the executable name: 

     atop -r /var/log/atop/atop_20200822 -PPRG | awk '$8 ~ /EssentialDaemon/ && $9 == "E"''

**Comment by Atoptool** [comment]
Similarly, you can check this for several days in one run:

    atopcat /var/log/atop/atop_202008?? | atop -r - -PPRG | awk '$8 ~ /EssentialDaemon/ && $9 == "E"'
