### ISSUE TITLE
interval cannot be customized anymore

### ISSUE THREAD

**Issue by Zugschlus** [Atoptool/atop#13]
This is me forwarding https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861874

The user suggests making the INTERVAL in atop.daily configurable from a defaults file.

The idiom should be something along:
`
#!/bin/bash

CURDAY=`date +%Y%m%d`
LOGPATH=/var/log/atop
BINPATH=/usr/bin
PIDFILE=/run/atop.pid
INTERVAL=600                            # interval 10 minutes

if [ -e "/etc/atop/defaults" ] ; then
  . /etc/atop/defaults
fi

`

So that the local user can create a defaults file and have the settings made there honored without the need to modify the script itself.

Greetings
Marc

**Comment by ThomasAH** [comment]
I'd like to have this again, too.
I run an interval of 60 seconds on some servers, and up to Debian jessie using the old /etc/default/atop was easy.

For now I just change /usr/share/atop/atop.daily, but this won't survive an update, so being able to set this in a config file (/etc/atop/atop-daily.conf or whatever name) would be nice.

**Comment by Atoptool** [comment]
Issue has been solved by introducing configuration file /etc/default/atop to overrule variables LOGOPTS, LOGINTERVAL and LOGGENERATIONS.
