### ISSUE TITLE
atop -r -PPRG -b <future time> should block until now == <future_time>

### ISSUE THREAD

**Issue by gleventhal** [Atoptool/atop#130]
If I run atop -r -PPRG -b 13:30 when it's 13:20 it will output 13:20 and exit.  It should either block until the time filter matches the time, or it should exit with an error in my opinion.

**Comment by Atoptool** [comment]
When running atop interactively (so same command line without -PPRG), it will show the screen with the last sample taken to enable you to press the 't' button to see new samples in the future. It would be inconsistent when atop behaves differently with the -P flag being used. In my opinion it is not an error.
Blocking until the future time is reached is not an option in my opinion either. Suppose that the future time is tomorrow or a week later (which is possible by specifying a date in the begin time as well), atop has to switch to the raw file of another (future) day, continuously polling if that raw file is already there.
