### ISSUE TITLE
Infiniband incorrect unit igbps/ogbps ?

### ISSUE THREAD

**Issue by jbd** [Atoptool/atop#131]
Hi,

from the manpage, ogbps should show the "Effective number of gigabits transmitted per second", but this is not the case:

```
11:19:32  controller port  busy ipack/s opack/s igbps ogbps maxgbps lanes  _ib_
11:19:33  mlx5_0        1    2% 23081.0 74422.0    38  2017     100     4
          mlx5_1        1    0%     0.0     0.0     0     0      10     4
11:19:34  mlx5_0        1    2% 23726.0 75429.0    39  2045     100     4
11:19:35  mlx5_0        1    2% 23811.0 75326.0    38  2042     100     4
11:19:36  mlx5_0        1    2% 23144.0 75431.0    38  2046     100     4
11:19:37  mlx5_0        1    2% 23475.0 75303.0    39  2041     100     4
11:19:38  mlx5_0        1    2% 23970.0 75469.0    38  2047     100     4
11:19:39  mlx5_0        1    2% 24397.0 75778.0    39  2054     100     4
11:19:40  mlx5_0        1    2% 23454.0 75421.0    38  2044     100     4
```
Jean-Baptiste

**Comment by jbd** [comment]
For the record, I'm using atop Version: 2.4.0 - 2019/01/12 20:37:57 from the Fedora EPEL repo.

**Comment by Atoptool** [comment]
Unfortunately, I have no access to systems with Infiniband.
Do you have an idea about what the proper value should be (e.g. from other tooling)?

Atop reads the information about Infiniband from subdirectories under the `/sys/class/infiniband` directory. Per port you can find the 'files' `..../counters/port_xmit_data` and `..../counters/port_rcv_data`. According to the website
[https://community.mellanox.com/s/article/understanding-mlx5-linux-counters-and-status-parameters]
the counter `port_xmit_data` means "Total number of data octets, divided by 4 (lanes), transmitted on all VLs.".

**Comment by Atoptool** [comment]
Issue will be reopened when more information is available.

**Comment by Atoptool** [comment]
Issue is clear now and solved.
