### ISSUE TITLE
atopacctd hasn't deleted shadow files 

### ISSUE THREAD

**Issue by AdamPioneer** [Atoptool/atop#132]
environment:

    atopacctd  version: 
    Version: 2.3.0 - 2017/03/25 09:59:59  <gerlof.langeveld@atoptool.nl>
    os:
    CentOS Linux release 7.2 (Final)

I met a problem when i using atop
Shadow files in the  /run/pacct_shadow.d directory will never be deleted.
There are a lot of shadow files in the  /run/pacct_shadow.d directory
Using gdb to debug, can find gcshadows function is never called.

Has anyone encountered this problem?

The following files is ltrace and strace log 
[strace_25367.log](https://github.com/Atoptool/atop/files/5249066/strace_25367.log)

[ltrace_25367.log](https://github.com/Atoptool/atop/files/5249064/ltrace_25367.log)
.

**Comment by AdamPioneer** [comment]
The following is /run/pacct_shadow.d directory info.
[root@centos /run/pacct_shadow.d]## ll|more
total 33609532
-rw-r--r-- 1 root root 640000 Aug 10 00:01 0000000000.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:02 0000000001.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:03 0000000002.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:04 0000000003.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:06 0000000004.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:07 0000000005.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:08 0000000006.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:09 0000000007.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:10 0000000008.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:11 0000000009.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:12 0000000010.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:13 0000000011.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:14 0000000012.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:15 0000000013.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:16 0000000014.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:18 0000000015.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:19 0000000016.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:20 0000000017.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:21 0000000018.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:22 0000000019.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:24 0000000020.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:25 0000000021.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:26 0000000022.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:27 0000000023.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:28 0000000024.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:30 0000000025.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:31 0000000026.paf
-rw-r--r-- 1 root root 640000 Aug 10 00:32 0000000027.paf

**Comment by AdamPioneer** [comment]
root cause: 
The system time jump causes the below judgment condition is always false.
`		/*
 		** verify if garbage collection is needed
		** i.e. removal of shadow files that are not in use any more
		*/
		if ( shadowbusy && time(0) > gclast + GCINTERVAL )
		{
			gcshadows(&oldshadow, curshadow);
			gclast = time(0);
		}`

**Comment by Atoptool** [comment]
Issue solved by checking time consistency.
