### ISSUE TITLE
Undocumented field in PRD samples

### ISSUE THREAD

**Issue by elynnyap** [Atoptool/atop#136]
The next-to-last field in the parseable output for PRD samples appears to be a constant "n":

https://github.com/Atoptool/atop/blob/25c6d641e3b6c4f424003d70b40b0239c0c2b10b/parseable.c#L773

`man atop` does not explain what this signifies, and suggests that `is_process` follows `TGID`. From reading the source code, it seems the actual order is `TGID`, "n", `is_process`.

https://github.com/Atoptool/atop/blob/25c6d641e3b6c4f424003d70b40b0239c0c2b10b/man/atop.1#L2284

What is this field, and can it be dropped or reflected in the documentation?

**Comment by Atoptool** [comment]
Fields in the parseable output will never be dropped to keep compatibility. Documentation has been corrected.
