### ISSUE TITLE
probably missing rm -f in atopacctd.init

### ISSUE THREAD

**Issue by Zugschlus** [Atoptool/atop#139]
Hi,

the init script for atopacct says:

```
  stop)
        # Check if atopacctd runs
        #
        if ps -e | grep -q atopacctd$
        then
                kill $(ps -e | grep atopacctd$ | sed 's/^ *//' | cut -d' ' -f1)
        fi
        rm /var/lock/subsys/atopacctd
        ;;
```

If stop is invoked on an already stopped daemon, the atopacctd file doesn't exist and rm emits an error message. This should either be rm -f, or the rm bracketed into a check whether the file exists.

Greetings
Marc

**Comment by Atoptool** [comment]
Issue is solved.
