### ISSUE TITLE
atop on stateless machine

### ISSUE THREAD

**Issue by jbd** [Atoptool/atop#140]
Hello,

I hope this is the correct place to ask. 

I'm using atop on stateless nodes, booting from a gold image using a network boot. To centralize atop raw logfiles I'm using rsync with a random delay via cron, multiple times per hour. I could also directly write the atop logfiles on a shared filesystem, but I'd like to keep atop alive even in case of shared filesystem outage.

While straightforward, this method has been working quite well for us but does not handle node reboot: a new atop logfile named `atop_20201203` for example will overwrite the content of the rsync target and I'll loose everything that happened before the reboot. 

I like the simplicity of rsync very much, and I'm quite reluctant to add logic to the synchronization process, like detecting the same filename, checking size, adding an adequate suffix as the destination target (ie: `rsync --foo atop_20201203 remote:atop_20201203.1`)

The simplest workaround I can think of is to add a suffix to the atop logfile, in the atop.daily file, locally on each node. Maybe using the epoch time since boot ?
```
CURDAY=$(date +%Y%m%d)_$(date --date="$(uptime -s)" +%s)
```
The only side effect I can think of on the top of my head is that atop -r without arguments won't work. I can live with that.

What do you think ? Any ideas or advice ? 

Thank you for your help,

Jean-Baptiste

**Comment by Atoptool** [comment]
I agree with your workaround. You might even consider to use the new 'atopcat' command to glue the logfiles of one day together again on the remote machine.

Another idea:
During the boot phase of the local machine, try to copy (rsync) an existing logfile for the current day from the remote machine to the local machine before starting atop locally again. If that succeeds, atop starts extending that logfile locally while at runtime it is rsync'ed with the remote machine again. When no logfile exists for today on the remote machine, the initial rsync will fail and a new logfile will be created locally by atop.
