### ISSUE TITLE
Duplicate use of 'h' option in atopsar

### ISSUE THREAD

**Issue by natoscott** [Atoptool/atop#152]
I noticed the 'pridef' declaration in atposar.c contains two entries for -h ('h') - Infiniband and the Apache web server stats.

By my reading of the code these need to be unique - I'm happy to open a PR to rectify this @Atoptool - which one should win out though, and any preference on the new option character for the other?  Thanks.

**Comment by Atoptool** [comment]
Thanks, flags should certainly be unique.
