### ISSUE TITLE
NVMe 100% busy, but IO is only about 10,000

### ISSUE THREAD

**Issue by pletharoe** [Atoptool/atop#153]
![20210508_210340](https://user-images.githubusercontent.com/22358721/117538562-bb7fa680-b041-11eb-96ac-7acf22058661.jpg)

As you can see, nvm2n1 and nvme0n1 are reading / writing about 10,000 / second, however they are reporting Busy 100%.  This is a much lower throughput than I expected, am I misunderstanding?  Are they really maxed out, or can I increase the load?

**Comment by Atoptool** [comment]
Being busy for 100% means that during the interval of 10 seconds, the NVMe drive was busy issueing I/O requests all the time. That does not mean that it can't handle more I/O requests if needed.
Apart from that, it is also relevant how much data is transferred by the 10,000 I/O operations per 10 seconds (not per second), so also have a look at the MBr/s and MBw/s together to see the MiB/s  throughput on this device.
