### ISSUE TITLE
How many interfaces atop logging in raw?

### ISSUE THREAD

**Issue by fessoga5** [Atoptool/atop#158]
Hello! I installed on a hypervisor and started - '/usr/bin/atop -R -w /var/log/atop/atop_20210531 30'.

The hypervisor has many 'tap*' interfaces. When i read atop file, i not found ~30% tap interfaces. 

Sry, my english. Why?

**Comment by Atoptool** [comment]
Currently there is a limit of 128 interfaces in atop (in raw logging and interactively).
