### ISSUE TITLE
Add posibility to sort on any column

### ISSUE THREAD

**Issue by Yanpas** [Atoptool/atop#169]
Problem: I need to filter out all threads that are running on core 6 (CPUNR = 6).

It would be handy if `<` and `>` buttons would change sorting column, like in classic top

**Comment by Atoptool** [comment]
Implementing a sorting possibility for any column would require a major redesign of atop.
Instead, you can use the parsable output e.g. to find all threads running on CPU6, like this:

`atop -Zy -PPRC | awk '$17 == 6 {print $5, $7, $8}'`

This command line shows for all threads running on CPU6 the current time ($5), the PID ($7) and the command name ($8) for a live measurement. Add the `-r` flag to produce this output for a recorded measurement (raw log).
