### ISSUE TITLE
Add option to disable sorting, or sort by device name rather than activity.

### ISSUE THREAD

**Issue by Mike-Benoit** [Atoptool/atop#17]
I don't see an option to prevent sorting completely in the man page. When reading columns on the far right it can be frustrating when the order of rows keeps changing because one drive has more activity than the other and it might keep swapping back and forth. So it would be nice to an option that sorts by device name perhaps and not activity to prevent things from "bouncing around".

atop rocks btw!

**Comment by Atoptool** [comment]
There is already an option to suppress sorting for device lines, i.e. interactive key 'F' or flag '-F'.
