### ISSUE TITLE
Shouldn't atop.daily be under /usr/libexec/atop/ rather than under /usr/share/atop/ ?

### ISSUE THREAD

**Issue by lockywolf** [Atoptool/atop#174]
In general, /usr/share/pkg/ is not really expected to have runnable executables, even the ones never expected to be run by the user/administrator.

Perhaps, /usr/libexec/ would be a better place.

**Comment by Atoptool** [comment]
The atop.daily script has been moved around between various locations in the past. There are quite some packages with scripts underneath the /usr/share/pkg directory. This might also vary depending on the Linux distribution.
