### ISSUE TITLE
files without license information

### ISSUE THREAD

**Issue by Zugschlus** [Atoptool/atop#179]
Hi,

atop 2.7.0 still has a lot of files without license information. From debian/copyright, this would be:

* 45atoppm
* atop.cronsysv
* atop.daily
* atop.default
* atop.init
* atop.service
* atopacct.service
* atopacct.init
* atopgpud
* atopgpu.service
* atop-pm.sh
* atop-rotate.service
* atop-rotate.timer
* Makefile
* netlink.c
* versdate.h
* version.c
* version.h
* prev/photoproc_20.h
* prev/photoproc_21.h
* prev/photoproc_22.h
* prev/photoproc_23.h
* prev/photoproc_24.h
* prev/photoproc_25.h
* prev/photoproc_26.h
* prev/protosyst_20.h
* prev/photosyst_21.h
* prev/photosyst_22.h
* prev/photosyst_23.h
* prev/photosyst_24.h
* prev/photosyst_25.h
* prev/photosyst_26.h
* versdate.h
* version.c
* version.h

I understand that it would be clumsy to touch all those files just for the sake of it, but maybe it would be possible to add a chapter to the README stating that all files not marked differently are Copyright Gerlof Langefeld 2007-2010 or something. That would make things easier for Debian.

Greetings
Marc

**Comment by Atoptool** [comment]
General copyright notice added to README, and separate license info added to netlink.c and atopgpud.
