### ISSUE TITLE
How should I make atop rotate logs daily

### ISSUE THREAD

**Issue by wangyihanlarry** [Atoptool/atop#187]
Hi,

I've installed the atop but failed to make the logs rotated in daily basis, it keeps logging the file in exactly the same file, what else should I do to make the daily rotating work? below is my atop configuration:

witihin /usr/share/atop/atop.daily

#!/bin/sh

LOGOPTS="-a"
LOGINTERVAL=2                           # default interval in seconds
LOGGENERATIONS=28                       # default number of days
LOGPATH=/data/log/atop                   # default log location

# allow administrator to overrule the variables
# defined above
#
DEFAULTSFILE=/etc/sysconfig/atop                # possibility to overrule vars

within /etc/sysconfig/atop  
LOGOPTS="-a"
LOGINTERVAL=2
LOGGENERATIONS=28
LOGPATH=/data/log/atop

I could only find one log under the path /data/log/atop, however, each time a new log will be generated when I restart the atop. I am not sure how should I make the log generate automatically in daily basis, should I add some commands in the crontab? would not atop take care of this?

my installation version is 
[root@TENCENT64 /]# atop -V
Version: 2.7.1 - 2022/01/08 12:48:36     <gerlof.langeveld@atoptool.nl>

and my os version is 
[root@TENCENT64 /]# cat /etc/redhat-release 
CentOS Linux release 7.2 (Final)
[root@TENCENT64 /]# uname -a
Linux TENCENT64.site 3.10.107-1-tlinux2_kvm_guest-0055-inject #3 SMP Tue Nov 30 21:35:41 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Atoptool** [comment]
When atop has been installed from the EPEL repository, you can modify options in the /etc/sysconfig/atop file (which you did). The atop.daily file is not used any more on systemd-based systems.
After installing atop, did you run the commands (especially the last one is needed for daily rotation):

`systemctl enable --now atop`
`systemctl enable --now atopacct`
`systemctl enable --now atop-rotate.timer`

**Comment by Atoptool** [comment]
Please reopen when new information is available.
