### ISSUE TITLE
ST column incorrectly shows 'N' for all tasks sporadically 

### ISSUE THREAD

**Issue by gleventhal** [Atoptool/atop#237]
For example:
```
host-A:0# atop -v -r -b 16:36 | grep -m 1 30047
30047 30039 username-1 domain_u 2023/02/13 04:00:00 N-   - S 1200% my-server    

host-A:0# atop -r -b 16:36 -e 16:37 -PPRG | awk '$7 == 30047 { print; exit }'
PRG host-A 1676306173 2023/02/13 16:36:13 10 30047 (my-server) S 16017 32771 30047 12 0 1676260800 (arg1 arg2) 30039 0 12 0 16017 32771 16017 32771 16017 32771 0 y 0 0 -

host-A:0# date -d @1676260800
Mon Feb 13 04:00:00 GMT 2023
```

Notice that the 16:36:13 sample shows "N-" in the UI, despite the parsable output showing a process epoch of 04:00:00
All tasks seem to report N- for this one sample despite having a contradictory epoch, and the 1200% CPU utilization seems off as well.

**Comment by Atoptool** [comment]
Please can you provide me with a raw logfile in which the issue occurs. I can not reproduce this myself.

**Comment by Atoptool** [comment]
Please reopen this issue when a raw logfile is available for further analysis.  Notice that the new command 'atophide' can be used to anonymize a raw logfile (should possibly be compiled on the target system to support the raw logfile format being used).
