### ISSUE TITLE
I upgrade to ncurses 6.1, atop layout broken.

### ISSUE THREAD

**Issue by ncaq** [Atoptool/atop#25]
I use Gentoo Linux.

I upgrade ncurses 6.0 to 6.1.

atop layout broken.

![screenshot-2018-03-06-13-37-18](https://user-images.githubusercontent.com/2913112/37014376-9a5e3e52-2143-11e8-89a6-e8e667fabc86.png)

atop version is 2.3.0-r1.

**Comment by fatexs** [comment]
Also same issue on Ubuntu 18.04 ncurses 6.1 and atop 2.3.0

**Comment by Zugschlus** [comment]
I see similiar behavior on Debian (KDE/konsole) as well. There seems to be a terminal dependency, in a plain xterm, things are just fine.

**Comment by oglueck** [comment]
reference to the Gentoo bug:
https://bugs.gentoo.org/651722

Note that it seems specific to konsole with the default TERM=xterm. It works when TERM=st or konsole etc.

**Comment by Atoptool** [comment]
Since no modifications have been made to the atop code related to screen handling, I wonder what has been modified in ncurses to introduce the broken layout.

**Comment by oglueck** [comment]
Looking at the "Depends on" of the Gentoo parent issue for the ncurses update https://bugs.gentoo.org/652080 you see that various applications misbehave with konsole with the new ncurses. I think the problem lies either in konsole or ncurses/terminfo and should be fixed there.

**Comment by doublex** [comment]
+1

**Comment by ncaq** [comment]
I use lilyterm.
I try `TERM=st atop`, it is worked.

**Comment by doublex** [comment]
@ncaq 
Thanks!!

**Comment by Atoptool** [comment]
Issue closed. Not an atop issue.

**Comment by ncaq** [comment]
I found reason.

> add rep to xterm-new, available since late 1996.
> [Announcing ncurses 6.1](https://www.gnu.org/software/ncurses/)
