### ISSUE TITLE
json API stability guarantee

### ISSUE THREAD

**Issue by patrickelectric** [Atoptool/atop#276]
The `-J` is great, but is there any guarantee that will not be break between versions ?
Developers may use it to create applications over, but... if it's going to break I'll not even start :rofl:

**Comment by Atoptool** [comment]
The output generated by the flags `-P` and `-J` is intended to remain unchanged. It might be extended with new counter values.

**Comment by patrickelectric** [comment]
@Atoptool, lovelly!
