### ISSUE TITLE
Missing container name with key 'j'

### ISSUE THREAD

**Issue by ben221199** [Atoptool/atop#286]
When pressing the 'j' key, I only see the CIDs of the containers. However, when I'm debugging the server, because I want to see why it uses 100% CPU and 100% Memory, I have to reboot the server and in that case, some Docker Swarm service containers will be removed an created again.

Is it possible to add the container name next to the container id, when reading my ATOP file after a reboot?

**Comment by Atoptool** [comment]
I can imagine that the container name is a useful addition. However, the container id can be obtained from the kernel information (from the UTS namespace that the containerized process is attached to), but the container *name* is maintained within Docker itself. Obviously there are ways (APIs) to retrieve this information from Docker, but besides Docker there are numerous other container implementations for which this has to be implemented as well requiring a huge effort.
