### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by Eugeny1** [Atoptool/atop#295]
Openwrt r24924, sunxi/cortexa7, my compilation of the main rep.

When starting atop system shows

```
[  timestamp] __vm_enough_memory: pid: xxx, comm: atop, no enough memory for allocation
Segmentation fault

```
Connected through the serial port with minicom using terminal VT102.
Unfortunately atop does not show its version when given -h flag. `opkg` shows 2.7.1-1.

`free` shows megabytes of available memory.

I suspect there's something wrong with the allocating memory for the screen buffer due to some issue with the terminal configuration.
Searched the web but did not find reports for it. I see the current version must be 2.10, so mine (openwrt's) must be slightly outdated.

**Comment by Atoptool** [comment]
When `atop` is started under root identity it tries to lock its memory to avoid being swapped out while you want to analyse memory consumption of other processes and system components. That might be a possible reason for the failing allocation. Is it possible to run `atop` with `strace` under OpenWRT to get a system call trace of this situation?

The version `atop` will be shown by using the `-V` flag.

**Comment by Atoptool** [comment]
Please reopen this issue when more information is available.

**Comment by Eugeny1** [comment]
To update the issue - it only exhibits through the serial port console (I was using minicom), if connecting using ssh tool works properly. I have tried with `strace` but it started looping and never ended to have kind of "complete" log. I did not investigate it further.
