### ISSUE TITLE
Filter Thread States with Q, not only Processes

### ISSUE THREAD

**Issue by gleventhal** [Atoptool/atop#296]
I very much like the ability to filter on Runnable or D state processes with Q R or Q D, but when I have thread view enabled, this becomes less useful.  Please filter all tasks, including threads when using Q, or add another key command to do so.  I want to see threads in the selected state as well, not only to filter on processes.  

Also, it would be nice to be able to sort by state in the UI.  But that's less important to me.   Thanks!

**Comment by Atoptool** [comment]
Issue solved, with the side effect that a process (i.e. the main thread) in state 'S' is also shown when one of its other threads is in state 'R' when the selection is for state 'R', even when thread view is currently not enabled.
