### ISSUE TITLE
Not able to get A100 GPU stats

### ISSUE THREAD

**Issue by pankajd-57** [Atoptool/atop#297]
I have Ubuntu 20.04 based system having NVIDIA A100 GPUs. I am able to get cpu stats, but not able to get GPU stats. Pleas help.

**Comment by pankajd-57** [comment]
HI,

Any pointers to this would be a great help.

**Comment by Atoptool** [comment]
Did you activate the `atopgpud` daemon as described in the `atop` man page (section `GPU STATISTICS GATHERING`)?

**Comment by pankajd-57** [comment]
thank you.  enabling atopgpud  worked. Is there a provision for collecting lustre client  disk io stats ?

**Comment by Atoptool** [comment]
Lustre client stats are currently not maintained by atop. It would be interesting to extend atop with these stats, but I do not have access to Lustre client systems myself.
