### ISSUE TITLE
suggested change to init script

### ISSUE THREAD

**Issue by Zugschlus** [Atoptool/atop#307]
Hi,

in Debian, we have been using this patch since 2016:

```
--- a/atop.init
+++ b/atop.init
@@ -7,8 +7,8 @@
#
### BEGIN INIT INFO
# Provides:             atop
-# Required-Start:      $local_fs
-# Required-Stop:       $local_fs
+# Required-Start:      $local_fs $remote_fs
+# Required-Stop:       $local_fs $remote_fs
# Default-Start:       2 3 4 5
# Default-Stop:                0 1 6
# Short-Description: Advanced system and process activity monitor
--- a/atopacct.init
+++ b/atopacct.init
@@ -7,8 +7,8 @@
#
### BEGIN INIT INFO
# Provides:             atopacct
-# Required-Start:      $local_fs
-# Required-Stop:       $local_fs
+# Required-Start:      $local_fs $remote_fs
+# Required-Stop:       $local_fs $remote_fs
# Default-Start:       2 3 4 5
# Default-Stop:                0 1 6
# Description:          This daemon switches on process accounting and
```

I had submitted that one in pre-github times via the web form but would like to have an URL that documents the forwarding. hence, re-submitting.

I am not sure whether this is still needed since most distributions have migrated to merged-/usr since 2016, but in a distribution that still uses the init script they might as well have /usr mounted via NFS.

**Comment by Atoptool** [comment]
I can not really judge if this modification introduces incompatibilities for other (init-based) distributions.
Do you have an opinion about that?

**Comment by Zugschlus** [comment]
I have never used a system that had its /usr on a network file system, but from a Debian point of view the omission of remote_fs would have been a bug from the very beginning.

**Comment by Atoptool** [comment]
Suggested change implemented.
