### ISSUE TITLE
Strange values in NET after atopconvert

### ISSUE THREAD

**Issue by chmyaf** [Atoptool/atop#308]
Hi!

I use PARSEABLE OUTPUT for load analysis and get data from various versions of atop. I'm converting them to version 2.10 format. If I received data from top 2.7.1 and converted it to 2.10 format, incorrect information is returned in the "NET upper" block. For example the number  of established connections at this moment (TCP) increases more than 10 times:

There are 19 connections here:
```
/opt/atop-2.7.1/atop -PNET -r atop_20240620|grep 'upper'|head -n 3|tail -n 2
NET nuc 1718831401 2024/06/20 00:10:01 600 upper 1901 1573 785 822 2653 2365 2653 0 0 0 117 0 19 1 0 67
NET nuc 1718832001 2024/06/20 00:20:01 600 upper 1721 1473 563 683 2300 2133 2299 0 0 0 97 0 19 5 0 70
```

Atopconvert:
```
/opt/atop-2.10.0/atopconvert atop_20240620 atop_20240620--2.10 
Version of atop_20240620: 2.7
Version of atop_20240620--2.10: 2.10
Samples converted: 55
```

There are already 1901 and 1721 connections here:
```
/opt/atop-2.10.0/atop -PNET -r atop_20240620--2.10 |grep 'upper'|head -n 3|tail -n 2 
NET nuc 1718831401 2024/06/20 00:10:01 600 upper 1573 1 0 31 2623 2353 2623 12 822 0 0 0 1901 0 67 0 0
NET nuc 1718832001 2024/06/20 00:20:01 600 upper 1473 5 0 11 2290 2127 2290 6 683 0 0 0 1721 0 70 0 0
```

**Comment by Atoptool** [comment]
In version 2.8 two counters have been added that were not properly converted from earlier log files (like log files from  version 2.7). This issue has been solved now. The current version of `atopconvert` will convert to version 2.11 by default, but with the option e.g. `-t 2.10` a conversion can be done to version `2.10`.
