### ISSUE TITLE
atop 2.7 is not backwards compatible with 2.4

### ISSUE THREAD

**Issue by sramakrishnan247** [Atoptool/atop#311]
Hey, firstly, thanks for creating atop and maintaining it as well.

I have been using `atop=2.4.0-3` while using Ubuntu-20.04 and recently upgraded to Ubuntu-22.04 and using `atop=2.7.1-1` now. I observed that with the upgraded atop, I cannot open older atop logs and have been hitting the following error:

```
 ubuntu@ip:~$ atop -r 20240708
raw file /var/log/atop/atop_20240708 has incompatible format
(created by version 2.4 - current version 2.7)
trying to activate /usr/bin/atop-2.4....
activation of /usr/bin/atop-2.4 failed!
```

Is there a workaround that I can use without depending on the older version?

**Comment by Zugschlus** [comment]
Your package should have converted the log file on installation. Either use atopconvert or (easier) delete the log, if you don't care about the data collected on July 8.

**Comment by sramakrishnan247** [comment]
Will try atopconvert as we need the logs. Thanks

**Comment by Atoptool** [comment]
Correct, `atopconvert` can be used to covert older logs.
