### ISSUE TITLE
Document the meaning of the timestamp in the top bar when using atop -r

### ISSUE THREAD

**Issue by martinvonwittich** [Atoptool/atop#313]
When I open a raw `atop` recording with `atop -r /var/log/atop/atop_<DATE>` and use the `b`/`t`/`T` keys to browse through the samples, `atop` displays the timestamp of the sample in the top bar, e.g.:

```
ATOP - host                 2024/07/24  13:00:02                 ----------------                  10m0s elapsed
```

For the longest time, I believed this timestamp to refer to the *start* of the sample, e.g. that the `13:00:02` here refers to a sample that spans 13:00 - 13:10. Apparently I was wrong about this, because when I switch to the `[v]arious` view, I see that processes have ENTIMEs somewhere between 12:50 - 13:00, so the timestamp does seem to refer to the *end* of the sample.

I've looked through `man atop` for an explanation of the timestamp, but I haven't found any. This seems to me like something that should be documented :)

**Comment by Atoptool** [comment]
The time stamp in the header line reflects the moment that the sample is taken/shown, consistently for live measurements and for viewing raw recordings. I added a description of the header line to the man page of `atop`.
