### ISSUE TITLE
atop cli cmd fails with 53 exit code

### ISSUE THREAD

**Issue by denizzzka** [Atoptool/atop#36]
Sometimes atop cli cmd fails with 53 exit code. After reboot it works ok.

```
denizzz@localhost ~/D/d/core [53]> atop -V                                                    Сб 25 авг 2018 10:59:19
Version: 2.3.0 - 2017/03/25 09:59:59     <gerlof.langeveld@atoptool.nl>
```

**Comment by Atoptool** [comment]
Is it possible that you are in a current directory with a very long pathname (> 1024 characters) at the moment that you start atop?
Does the same issue happen if you start atop like:
$   cd  /tmp
$   atop

**Comment by denizzzka** [comment]
> Is it possible that you are in a current directory with a very long pathname (> 1024 characters) at the moment that you start atop?

No, usually I start atop at my home dir

> Does the same issue happen if you start atop like [...]

Yes

**Comment by denizzzka** [comment]
Maybe it is importan that I run atop on "zfs on linux" root.

**Comment by Atoptool** [comment]
I added additional error messages to the source code and give exit code 54 or 55 in cases where only exit code 53 was given previously. Can you try to reproduce this issue with the new code?

**Comment by Atoptool** [comment]
Exit code 53 deals with gathering all process and thread info. This part is redesigned now, also for performance reasons (long time before first atop screen appears on larger systems). Issue closed. Please reopen when a similar problem occurs with the current version.
