### ISSUE TITLE
fails to build with gcc-8.2.1

### ISSUE THREAD

**Issue by rosset** [Atoptool/atop#37]
[filiperosset@raw atop]$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC)
[filiperosset@raw atop]$ make -Wall
cc -O2 -I. -Wall     -c -o atop.o atop.c
atop.c:274:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
 static const char rcsid[] = "$Id: atop.c,v 1.49 2010/10/23 14:01:00 gerlof Exp $";
                   ^~~~~
cc -O2 -I. -Wall     -c -o version.o version.c
cc -O2 -I. -Wall     -c -o various.o various.c
various.c:101:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
 static const char rcsid[] = "$Id: various.c,v 1.21 2010/11/12 06:16:16 gerlof Exp $";
                   ^~~~~
cc -O2 -I. -Wall     -c -o deviate.o deviate.c
deviate.c:171:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
 static const char rcsid[] = "$Id: deviate.c,v 1.45 2010/10/23 14:02:03 gerlof Exp $";
                   ^~~~~
cc -O2 -I. -Wall     -c -o procdbase.o procdbase.c
procdbase.c:61:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
 static const char rcsid[] = "$Id: procdbase.c,v 1.8 2010/04/23 12:19:35 gerlof Exp $";
                   ^~~~~
cc -O2 -I. -Wall     -c -o acctproc.o acctproc.c
acctproc.c:116:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
 static const char rcsid[] = "$Id: acctproc.c,v 1.28 2010/04/23 12:20:19 gerlof Exp $";
                   ^~~~~
cc -O2 -I. -Wall     -c -o photoproc.o photoproc.c
photoproc.c:139:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
 static const char rcsid[] = "$Id: photoproc.c,v 1.33 2010/04/23 12:19:35 gerlof Exp $";
                   ^~~~~
cc -O2 -I. -Wall     -c -o photosyst.o photosyst.c
photosyst.c: In function ‘lvmmapname’:
photosyst.c:1482:19: error: called object ‘major’ is not a function or function pointer
     dmp->major  = major(statbuf.st_rdev);
                   ^~~~~
photosyst.c:1437:25: note: declared here
 lvmmapname(unsigned int major, unsigned int minor,
            ~~~~~~~~~~~~~^~~~~
photosyst.c:1483:19: error: called object ‘minor’ is not a function or function pointer
     dmp->minor  = minor(statbuf.st_rdev);
                   ^~~~~
photosyst.c:1437:45: note: declared here
 lvmmapname(unsigned int major, unsigned int minor,
                                ~~~~~~~~~~~~~^~~~~
At top level:
photosyst.c:152:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
 static const char rcsid[] = "$Id: photosyst.c,v 1.38 2010/11/19 07:40:40 gerlof Exp $";
                   ^~~~~
make: *** [<builtin>: photosyst.o] Error 1
[filiperosset@raw atop]$

**Comment by Atoptool** [comment]
Issue solved by providing own macro's.

**Comment by rosset** [comment]
is this patch better, maybe? 

https://github.com/Atoptool/atop/commit/414127c03669b4eedc85778a7bff80cf601311d8.patch

**Comment by Atoptool** [comment]
Yes it is. It has been merged.

**Comment by Zugschlus** [comment]
I assume that glibc 2.8 is meant, we have this issue in Debian as well, http://bugs.debian.org/916013. Can we have a new release please?
