### ISSUE TITLE
An improved service file without atop.daily

### ISSUE THREAD

**Issue by jo-so** [Atoptool/atop#38]
I've improved my *atop.service* a little bit to don't use *atop.daily*. Maybe, this is helpful for you. Otherwise silently close this issue.
```
[Unit]
AssertPathExists=/usr/bin/atop

[Service]
PIDFile=/run/atop.pid
ExecStart=
ExecStart=/bin/sh -c 'exec /usr/bin/atop -w /var/log/atop/atop_`date +%%Y%%m%%d` 60'
ExecStartPost=/bin/sh -c 'echo $MAINPID > /run/atop.pid'
ExecStartPost=/usr/bin/find /var/log/atop -name "atop_*" -mtime +28 -exec rm {} \; -printf "Removed " -print
```

**Comment by Atoptool** [comment]
This solution might work, but I wonder what the improvement is.
The atop.daily script will be called anyhow every day at midnight to terminate the currently running atop and start a new incarnation for the new day. To preserve consistency, the initial startup can be done by the same script.
