### ISSUE TITLE
Problem with numerical scaling

### ISSUE THREAD

**Issue by r4m0n** [Atoptool/atop#39]
I'm having a formatting issue with the RDDSK and WRDSK stats, where if there's ~10M/s or more usage, the stats render as 0.0G/s.

Tried to isolate the issue, but I'm not certain exactly where the problem is, [maybe around here?](https://github.com/Atoptool/atop/blob/master/various.c#L452) Something might be overflowing, anyone more familiar with the code can take a look?

**Comment by yk144** [comment]
hi, I have the same problem. take a look at this PR
https://github.com/Atoptool/atop/pull/64

**Comment by Atoptool** [comment]
Solved by PR #64
