### ISSUE TITLE
atop failed with "Malloc failed for 1826553824 deviated tasks"

### ISSUE THREAD

**Issue by vinc17fr** [Atoptool/atop#41]
Under Debian unstable, I got the following error after a few minutes:

    zira:~> atop                                                          <21:09:41
    Malloc failed for 1826553824 deviated tasks
    zsh: exit 13    atop
    zira:~[13]>                                                           <21:13:02

The problem is not the malloc failure, but its cause, which is the huge number of tasks.

My bug report in the Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913910

**Comment by Atoptool** [comment]
Does this problem occur every time that you start atop on this system or just once?
Can you give me an idea about how many processes are usually running on this system?

**Comment by vinc17fr** [comment]
I can reproduce the problem, and on another machine too:

     Malloc failed for -1976328064 deviated tasks

About 300 processes are running on the system. This seems to occur at least when upgrading packages (which are not dependencies) with aptitude, but I don't see how this could be related.

MPFR's configure script also makes atop fail. This might be related to shell scripts, which execute many commands.

**Comment by vinc17fr** [comment]
With the type mismatches fixed (see PR #42), I can get:

    Malloc failed for 140728114819416 deviated tasks

Well, I assume that there's something wrong in the accounting. This may not be the cause, but the failure of system/library calls is no checked. For instance, in `acctprocnt`:

           (void) fstat(acctfd, &statacc);

**Comment by Zugschlus** [comment]
I have to agree on that count now. I see the issue as well now, especially when Debian updates are runinng. I also gues that this might be somehow related to many short-lived processes.

Gerlof, do you have any idea how to debug this? I guess that the "Malloc failed" is a rather generic errr message that can be caused from a gazillion of code paths in atop, right? I am willing to build and run a version with added debug info.

Could it be possible to have atop dump core in this case, that would at least allow a backtrace.

**Comment by Atoptool** [comment]
It is strange that too many terminated processes might be the cause of this issue, because atop will only handle about 63000 terminated processes maximum per interval. If more processes have been found in the process accounting file(s) per interval, they will be skipped so no space is malloc'ed for them.
Anyhow, I will try to have a debug version available later on this week to find the reason of that huge number of deviated processes.

**Comment by Atoptool** [comment]
I also added debug statements to acctproc.c now.
When you activate the debug statements, please run atop with stderr redirection to a file.

**Comment by vinc17fr** [comment]
I've rebuilt `atop` with debug code: after `make clean`:

    $ make
    cc -O2 -I. -Wall  -DDEBUGNRPROC    -c -o atop.o atop.c
    [...]

but I still get a single message like `Malloc failed for 656313376 exited processes` on stderr.

**Comment by vinc17fr** [comment]
If I remove the `if` lines associated with the debug messages, I get:

    atopacctd cur: st_size: 180544, acctsize: 0
    atopacctd cur: st_size: 180608, acctsize: 180544
    atopacctd cur: st_size: 263936, acctsize: 180608
    atopacctd cur: st_size: 474560, acctsize: 263936
    Malloc failed for 140728978937208 deviated tasks

**Comment by vinc17fr** [comment]
Some details... In `atop.c`, I have with my debug messages:
```
			curpexit = malloc(nprocexit * sizeof(struct tstat));
                        fprintf(stderr, "atop[3]: nprocexit: %lu\n", nprocexit);
			ptrverify(curpexit,
			          "Malloc failed for %lu exited processes\n",
			          nprocexit);
                        fprintf(stderr, "atop[4]: nprocexit: %lu\n", nprocexit);
```
and the output to stderr is:

    [...]
    atop[3]: nprocexit: 4876
    Malloc failed for 140729359512808 exited processes

I don't know why, but probably not a compiler bug since I can reproduce the same issue with clang.

**Comment by vinc17fr** [comment]
If I replace the `ptrverify` call like this:
```
                  curpexit = malloc(nprocexit * sizeof(struct tstat));
                  fprintf(stderr, "atop[3]: nprocexit: %lu\n", nprocexit);
                  if (!curpexit)
                    {
                      acctswoff();
                      netatop_signoff();
                      if (vis.show_end)
                        (vis.show_end)();
                      fprintf(stderr, "Malloc failed for %lu exited processes\n",
                              nprocexit);
                      exit(13);
                    }
                  fprintf(stderr, "atop[4]: nprocexit: %lu\n", nprocexit);
```
I get:

    [...]
    atop[3]: nprocexit: 10334
    Malloc failed for 10334 exited processes

So this looks like 2 different issues: one with the `ptrverify` call and one with the failed `malloc`. Even with
```
                  volatile size_t s = nprocexit * sizeof(struct tstat);
                  fprintf (stderr, "size = %zu\n", s);
                  curpexit = malloc(s);
```
I get:

    [...]
    size = 7143024
    atop[3]: nprocexit: 9111
    Malloc failed for 9111 exited processes

I cannot understand this failure with such a small size. Unless there is a memory corruption, which could explain everything...

**Comment by vinc17fr** [comment]
If I comment out the `mlockall` line, the failure disappears. Could the `malloc` failure be due to a limitation on the number of locked pages?

**Comment by vinc17fr** [comment]
Indeed, the limit is 16 MB by default. If I increase the hard limit to 65536 in `/etc/security/limits.conf` and set the soft limit to 64M in my shell, the malloc failure disappears.

**Comment by Atoptool** [comment]
Thanks for the analysis, Vincent! Great! You are right that there are two separate problems:
1) Malloc fails when atop is not running with superuser privs and the soft limit for lockable memory is above a certain threshold. I can reproduce this problem now and isolate it in a small program.
I modified the code of atop to solve the issue. Can you please test to see if the modification works?
2) The ptrverify does not work properly and prints strange values. I will dive into this further.

**Comment by Zugschlus** [comment]
Thank you both for isolating this issue without me interfering ;-)  Splendid work.

@Atoptool, please remember to cut a new release and to ping me with it so that it can be uploaded in time for Debian buster.

Greetings
Marc
