### ISSUE TITLE
CPU % usage column is misaligned when a process uses ≥1000% CPU

### ISSUE THREAD

**Issue by kepstin** [Atoptool/atop#49]
I noticed this when building rust recently. Affects the atop 2.4.0 release.
![screenshot from 2019-01-31 20-49-03](https://user-images.githubusercontent.com/38788/52097738-2fe15a80-259a-11e9-8d2c-4e092dcddbd7.png)

**Comment by Atoptool** [comment]
Issue has already been solved in atop 2.6
