### ISSUE TITLE
cannot  get statistical report of  resource consumption cross  multi-days!!!

### ISSUE THREAD

**Issue by gitbobo** [Atoptool/atop#53]
Do you want to get the overview of last week?  
atop can only read one day  log, then I CANNOT `atopsar -A -c`

**Comment by Atoptool** [comment]
Overviews can be produced with the new command 'atopcat' that concatenates raw logfiles that can be transferred to atop/atopsar via a pipe.
E.g. to see the CPU utilization during a 7-day period:

    atopcat /var/log/atop/atop_2020021[0-6]  |  atopsar -c  -r -
