### ISSUE TITLE
"ipc notavail" warning in version 2.4

### ISSUE THREAD

**Issue by randallsevery** [Atoptool/atop#56]
I recently upgraded several installations of atop from version 2.3.0 to version 2.4.0.  I noticed that the column with "#tlspu 0" at the top no longer shows guest percentages, but now shows the warning "ipc notavail".  Is this something that is configurable in atop or is it a bug?

**Comment by Atoptool** [comment]
The counter "#tslpu" is a value in the PRC line. Its appearance is not modified in atop 2.4.
The percentage "guest" can be found in the CPU line. In that same line a new counter "ipc" is introduced which indeed has a higher precedence as the "guest" counter. So with the same screen width it might be that the "ipc" counter is shown instead of the "guest" counter. When you widen your screen, the "guest" counter will also appear again as an additional column.
And yes, it is possible to configure the columns and their priority (see "man atoprc").

**Comment by Atoptool** [comment]
Please be aware that the system-level statistics (upper part of the atop output) have NO columns at all. Every line has its own counters, e.g. the counter #tslpu has the value 0 in the output above. When widening the window, counters can even be shifted to other 'columns'.
In the process-level statistics (lower part of the atop output) does use columns with a header line on top of the values!

**Comment by Atoptool** [comment]
When you widen the window, you will see the 'guest' percentage again in the lines with the 'CPU' or 'cpu' labels (but probably not below the '#tslpu' counter in the PRC line).

**Comment by randallsevery** [comment]
No matter how wide I make the window the columns still show up as in the screenshot shown above.  But the exact layout of the counters and columns are not my main concern.  When I run atop, I usually only pay attention to the highlighted (green in the examples above) entries, since in the past those would indicate problems on the server that I might need to take action on.  So when everything is working smoothly, I would expect atop to display only normal colored text (yellow in the examples above).  How can I get ride of the "ipc notavail" entries, which I have to keep looking at to see if they are a problem that I need to deal with, since presumably it's not really a problem, just something that's not available?  That's the same issue I have with the NVME disk busy problem outlined in issue #47, since it always looks like I have a major disk problem on the server, and I have to remember to ignore that and use other tools to make sure the disks are operating normally.

**Comment by Atoptool** [comment]
Atop uses a green color for information messages, like 'ipc notavail' which is not serious at all (just a missging metric). A cyan color is used for resources that are almost overloaded and a red color is used for resources that are overloaded. What I see in your output samples above is that red colored metrics are for some reason green colored, which means that with this color scheme you can not distinguish between informational messages (green) and serious overloads (cyan/red).
