### ISSUE TITLE
atop: logging writing to a full disk ?

### ISSUE THREAD

**Issue by e-ferrari** [Atoptool/atop#58]
Hi,
i'm using atop 2.2-2.1 on a SLES 12 SP4 HA-Cluster. 
I'm logging each second. This creates of course some waste of disk space and some CPU time, but i have enough cores and only a few logfiles are kept, the rest is discarded.
Some days ago i had the problem that several virtual machines (kvm) were paused, all at the same moment.
I *think* that a logical volume in which i store temporary some snapshots filled up, but i'm not sure because the snapshots are created by a script and at the end of the script they are deleted.
I'm thinking now of looking in atop if data is still written to that LV after the time i got e-Mails from my monitoring system that the virtual machines don't respond any longer.
My question is now: does atop monitor write requests to a full disk/LV ?
Maybe as a kind of "Trying to write" ?

Bernd

**Comment by Atoptool** [comment]
When a process writes to a filesystem/disk that is full, the write system call will fail and is not logged as a valid write. Usually applications will stop trying to do more writes after a failing write, but even when application keep on trying to write to a full disk the failing write system calls are not logged as "trying to write". Therefore, writing to a full disk can not be discovered via the output of atop.
