### ISSUE TITLE
atopsar stalled due to corrupt atop file

### ISSUE THREAD

**Issue by anujgtm1** [Atoptool/atop#63]
We have a custom script that calls atopsar to collect system metrics.
However, for certain days, the call to atopsar stalls (the process keeps on running and no response is obtained) and does not continue. Killing these atopsar commands result in \<defunct\> processes.
Upon further inspection, we found out that this is being caused due to corrupt atop file. We could not pinpoint or replicate the condition in which the file is corrupted, but I have attached the corrupt file here.
The commands running atopsar are:
1. atopsar -xG -b `date --date=\"-19 minutes\" +%H:%M` | tail -2
2. atopsar -xD -b `date --date=\"-19 minutes\" +%H:%M` | tail -2
3. atopsar -xO -b `date --date=\"-19 minutes\" +%H:%M` | tail -2

[atop_20190509.zip](https://github.com/Atoptool/atop/files/3276249/atop_20190509.zip)

**Comment by Atoptool** [comment]
This logfile has been written by atop version 1.26 (from 2010) which is not supported any more. Could you please provide a logfile that has been written by a newer version of atop?

**Comment by Atoptool** [comment]
No new information received.
