### ISSUE TITLE
avio metric questions

### ISSUE THREAD

**Issue by starp128** [Atoptool/atop#66]
Dear atop developer,

Hi, I am confused that 'avio' metric seems not as the document said. 

The manual says "average number of milliseconds needed by a request (`avio') for seek, latency and data transfer". So I expect that avio should be something like await of iostat. But it turn out they are not(you could find it by using fio with iodepth>1). await represent the average time for IO request. But avio is not. Maybe it it not designed that way. But the manual of atop is misleading. 

I try to find the different of avio and await. It seem avio is calculated by io_ms/iotot. io_ms is get from io_tics from /proc/diskstat which is as the kernel document says:
io_ticks        milliseconds  total time this block device has been active
（see kernel document Document/block/stat.txt. ） It do not increase if we have multiple IO inflight at same time. While await is calculated by
((sdc->rd_ticks - sdp->rd_ticks) + (sdc->wr_ticks - sdp->wr_ticks)) /((double) (sdc->nr_ios - sdp->nr_ios))  (see source common.c in sysstat v10.1.5).

So please give some help explaining avio.

**Comment by Atoptool** [comment]
I think both metrics ('avio' of atop and 'avwait' of iostat) are useful and represent different points-of-view. Suppose that two read requests are (partly) handled in parallel and each of these requests requires 2 milliseconds, like this:

           |----2ms----|    
              |----2ms----|
           |==========|   --> suppose 2.4 seconds elapsed

According iostat the 'avwait' (average wait per request) is 2 ms. From the application point-of-view, this value shows that both applications has been waiting 2 ms for their I/O request to complete. So 'avwait' reflects the wait time for the application.
According atop the 'avio' is 2.4/2 = 1.2 ms. From a disk point-of-view, this value shows that the disk is capable of handling 2 I/O requests in 2.4 ms, so an average of 1.2 ms per I/O request (with seek/latency/transfer in overlap). That's what the manual page of atop describes.
