### ISSUE TITLE
Consider using the precise pressure stall information ("total" collumn)

### ISSUE THREAD

**Issue by sourcejedi** [Atoptool/atop#72]
E.g. in practice, the "10 second average" takes several ten second intervals in order to update fully.  You can test this with IO pressure: start an IO hog on an idle system.

Have you considered using the running "total" column from `/proc/pressure/*`, to get the precise average pressures over the atop interval?  I think this could be more helpful, particularly when analyzing atop log files.

The kernel can't calculate the real "recent average" unless it keeps a cyclic buffer of historical values, which it does not bother to do.  Instead it <del>works similar</del> uses the exact same function as  the load average ([EWMA](https://unix.stackexchange.com/a/8897/29483)).

---

> The cpu file contains one line:
> 
> 	some avg10=2.04 avg60=0.75 avg300=0.40 total=157656722
> 
> The averages give the percentage of walltime in which one or more
> tasks are delayed on the runqueue while another task has the
> CPU. They're recent averages over 10s, 1m, 5m windows, so you can tell
> short term trends from long term ones, similarly to the load average.
> 
> The total= value gives the absolute stall time in microseconds. This
> allows detecting latency spikes that might be too short to sway the
> running averages. It also allows custom time averaging in case the
> 10s/1m/5m windows aren't adequate for the usecase (or are too coarse
> with future hardware).

**Comment by Atoptool** [comment]
I agree that the pressure percentage for the entire interval is most important. Atop and atopsar have been modified.
