### ISSUE TITLE
cannot read raw logs from pipe

### ISSUE THREAD

**Issue by davidberard98** [Atoptool/atop#73]
Atop sometimes fails when reading from a raw file which is a pipe - for example something like `atop -r myfifo -P cpu` along with `cat atop_log > myfifo` will sometimes fail.

In `atopconvert.c` many of the reads do something like this:

```c
    if ( read(rawfd, compbuf, complen) < complen)
    {
        free(compbuf);
        fprintf(stderr,
            "Failed to read %d bytes for system\n", complen);
        return 0;
    }
```

In pipes/fifos it is expected that `read` may read less than `complen` bytes even if more bytes might be available later

**Comment by gleventhal** [comment]
This is addressed by my pending pull request: https://github.com/Atoptool/atop/pull/69

**Comment by gleventhal** [comment]
If you're curious, the reason it fails is because you cannot seek on a named pipe and atop uses lseek() constantly.

**Comment by davidberard98** [comment]
I think that the issue here is slightly different; I wrote a bash script which replicates this behavior even after pull request #69 is included.

```bash
#!/bin/bash

# demo.sh: demonstrate read() issue
# Usage: bash demo.sh [atop binary path] [atop log path]
#
# What it does:
#   - write and compile demo.c
#   - makes a named pipe
#   - starts a process for demo.c, which writes small chunks to the pipe periodically.
#   - runs atop -r [pipe] -P cpu
#
# Atop exits with an exit code even with https://github.com/Atoptool/atop/pull/69

if [[ "$#" -ne "2" ]]; then
    echo "Usage: bash demo.sh [atop binary path] [atop log path]"
    exit 1;
fi

bytes=1571

cat > demo.c << EOF
#define _BSD_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

/*
 * usage: ./demo [infile] [outfifo] [number of bytes to write]
 */
int main(int argc, char ** argv)
{
    if (argc != 4)
    {
        return 1;
    }
    size_t bytes = strtol(argv[3], NULL, 10);

    FILE * f = fopen(argv[1], "rb");
    fseek(f, 0, SEEK_END);
    size_t sz = ftell(f);
    rewind(f);

    char * buf = malloc(sz);
    fread(buf, 1, sz, f);

    fclose(f);

    FILE * g = fopen(argv[2], "wb");
    size_t cur = 0;

    while (cur < sz)
    {
        size_t amt = bytes;
        if (sz - cur < bytes)
        {
            amt = sz - cur;
        }

        size_t n = fwrite(buf + cur, 1, amt, g);
        cur += n;

        printf("Just wrote %lu bytes\n", n);

        usleep(100*1000);
    }

    fclose(g);

    return 0;
}
EOF

gcc -std=c11 demo.c -o demo

echo "Done compiling"

rm demofifo
mkfifo demofifo
./demo $2 demofifo $bytes & 
sleep 1

echo "Starting atop"

$1 -r demofifo -P cpu

ret=$?

echo "ATOP EXITED WITH $ret"

pkill -fo demofifo
```

**Comment by gleventhal** [comment]
My commit is to prevent a segfault, exiting with cleanstop, exit code 7, not to allow reading from a named pipe.  atop uses lseek all the time, named pipes are not seekable so the atop code would have to be majorly changed to support using a named pipe as the rawlog.

**Comment by Atoptool** [comment]
It is possible to read raw data from named pipes now. However, in an interactive session with atop it is not possible to reset ('r'), to branch to a time ('b'), nor to go to a previous sample ('T'). With atopsar, only one report can be generated (not a combination of reports in one go).
