### ISSUE TITLE
Do not change owner to root

### ISSUE THREAD

**Issue by paulmenzel** [Atoptool/atop#76]
For users wanting to build Atop themselves, or for build tests with unprivileged users, explicitly calling `chown root …` is problematic.

https://github.com/Atoptool/atop/blob/3e0b68cb9858a16749c98c3d399d2373e239caa6/Makefile#L146-L159

I think, it’s common practice to keep the owner of binaries the same as the build user.

**Comment by Atoptool** [comment]
Issue solved.

**Comment by paulmenzel** [comment]
Thank you.

Resolved by commit https://github.com/Atoptool/atop/commit/28201dabbf443fb5edf0c9033e65d4741cf09162 (Do not change owner to root in Makefile (issue #76)).
