### ISSUE TITLE
virtual network interfaces shown as 10mbit

### ISSUE THREAD

**Issue by pooh22** [Atoptool/atop#83]
## problem

It seems that atop shows the vnet interfaces on a qemu+kvm host system as 10mbit, even though there is no actual physical link speed. When more than 10mbit is transported through the interface, the line shows up as red, but there is no actual problem.

## desired output

I would prefer the device interface speed to be shown as "virt" or something similar, so no indication of speed is given where not actually present. Also the line colour should only turn red if the througput is equal to the speed of the physical interface connected to the bridge or to the limit imposed by the VM configuration (bandwidth limiters).

**Comment by fmikker** [comment]
Just the issue I was about to report, but with at vpn device in my case:
```
NET | tun0	7%  |              | pcki 3076639  | pcko 2055337 |               | sp   10 Mbps | si  722 Kbps  | so   36 Kbps |               | coll       0 |  mlti       0 | erri       0 |  erro       0 | drpi	   0 |  drpo	   0 |
```

**Comment by Atoptool** [comment]
Issue has been solved by verifying the physical address of a network interface.
