### ISSUE TITLE
default location for LOGPATH will not work

### ISSUE THREAD

**Issue by arielnh56** [Atoptool/atop#85]
Some time ago I submitted https://github.com/Atoptool/atop/pull/59 to request that the LOGPATH declaration in atop.daily be moved before DEFAULTSFILE is read. While this hasn't been accepted, I do see that in https://github.com/Atoptool/atop/commit/e34478820e033a9e581ed601245fef2ae60878b2 you have added LOGPATH into the defaults file. 

I humbly submit that that's a NOOP unless LOGPATH is not hardcoded to another value after the defaults file is sourced.

**Comment by Atoptool** [comment]
Pull request #59 has been accepted.
